# Form implementation generated from reading ui file 'create_account.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6.QtWidgets import (QDialog, 
                             QLineEdit, 
                             QLabel, 
                             QPushButton)
from PyQt6.QtGui import QFont
from PyQt6.QtCore import (QRect, 
                          QMetaObject, 
                          QCoreApplication)


class Create_Account(QDialog):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(479, 616)
        Form.setStyleSheet("QWidget {\n"
"        background-color: #333333;\n"
"        color: #ffffff;\n"
"        border: none;\n"
"    }\n"
"    QPushButton {\n"
"        background-color: #4d4d4d;\n"
"        border: 1px solid #4d4d4d;\n"
"        border-radius: 4px;\n"
"        color: #ffffff;\n"
"        padding: 5px;\n"
"    }\n"
"    QPushButton:hover {\n"
"        background-color: #5a5a5a;\n"
"        border: 1px solid #5a5a5a;\n"
"    }\n"
"    QCheckBox {\n"
"        color: #ffffff;\n"
"    }\n"
"    QLineEdit {\n"
"        background-color: #4d4d4d;\n"
"        border: 1px solid #4d4d4d;\n"
"        color: #ffffff;\n"
"        padding: 5px;\n"
"        border-color: #ffffff;\n"
"        border-radius: 6px;\n"
"    }\n"
"    QTextEdit {\n"
"        background-color: #4d4d4d;\n"
"        border: 1px solid #4d4d4d;\n"
"        color: #ffffff;\n"
"        padding: 5px;\n"
"    }\n"
"    QProgressBar {\n"
"        border: 1px solid #444444;\n"
"        border-radius: 7px;\n"
"        background-color: #2e2e2e;\n"
"        text-align: center;\n"
"        font-size: 10pt;\n"
"        color: white;\n"
"    }\n"
"    QProgressBar::chunk {\n"
"        background-color: #3a3a3a;\n"
"        width: 5px;\n"
"    }\n"
"    QScrollBar:vertical {\n"
"        border: none;\n"
"        background-color: #3a3a3a;\n"
"        width: 10px;\n"
"        margin: 16px 0 16px 0;\n"
"    }\n"
"    QScrollBar::handle:vertical {\n"
"        background-color: #444444;\n"
"        border-radius: 5px;\n"
"    }\n"
"    QScrollBar:horizontal {\n"
"        border: none;\n"
"        background-color: #3a3a3a;\n"
"        height: 10px;\n"
"        margin: 0px 16px 0 16px;\n"
"    }\n"
"    QScrollBar::handle:horizontal {\n"
"        background-color: #444444;\n"
"        border-radius: 5px;\n"
"    }\n"
"    QTabWidget {\n"
"        background-color: #2e2e2e;\n"
"        border: none;\n"
"    }\n"
"    QTabBar::tab {\n"
"        background-color: #2e2e2e;\n"
"        color: #b1b1b1;\n"
"        padding: 8px 20px;\n"
"        border-top-left-radius: 5px;\n"
"        border-top-right-radius: 5px;\n"
"        border: none;\n"
"    }\n"
" \n"
"    QTabBar::tab:selected, QTabBar::tab:hover {\n"
"        background-color: #3a3a3a;\n"
"        color: white;\n"
"    }")
        self.lineEdit_username = QLineEdit(parent=Form)
        self.lineEdit_username.setGeometry(QRect(10, 90, 451, 51))
        self.lineEdit_username.setObjectName("lineEdit_username")
        font = QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.lineEdit_username.setFont(font)
        self.label_username = QLabel(parent=Form)
        self.label_username.setGeometry(QRect(20, 30, 91, 41))
        font = QFont()
        font.setPointSize(14)
        self.label_username.setFont(font)
        self.label_username.setObjectName("label_username")
        self.label_password = QLabel(parent=Form)
        self.label_password.setGeometry(QRect(20, 170, 91, 41))
        font = QFont()
        font.setPointSize(14)
        self.label_password.setFont(font)
        self.label_password.setObjectName("label_password")
        self.lineEdit_password = QLineEdit(parent=Form)
        self.lineEdit_password.setGeometry(QRect(10, 230, 451, 51))
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.lineEdit_password.setEchoMode(QLineEdit.EchoMode.Password)
        self.lineEdit_password.setFont(font)
        self.label_password_2 = QLabel(parent=Form)
        self.label_password_2.setGeometry(QRect(20, 310, 161, 41))
        font = QFont()
        font.setPointSize(14)
        self.label_password_2.setFont(font)
        self.label_password_2.setObjectName("label_password_2")
        self.lineEdit_password_2 = QLineEdit(parent=Form)
        self.lineEdit_password_2.setGeometry(QRect(10, 370, 451, 51))
        self.lineEdit_password_2.setObjectName("lineEdit_password_2")
        self.lineEdit_password_2.setEchoMode(QLineEdit.EchoMode.Password)
        self.lineEdit_password_2.setFont(font)
        self.pushButton_create = QPushButton(parent=Form)
        self.pushButton_create.setObjectName("pushButton_login")
        self.pushButton_create.setGeometry(QRect(10, 450, 451, 41))
        font = QFont()
        font.setPointSize(14)
        self.pushButton_create.setFont(font)
        self.pushButton_create.setStyleSheet("QPushButton {\n"
"        background-color: #2643ff;\n"
"        border: 1px solid #4d4d4d;\n"
"        border-radius: 4px;\n"
"        color: #ffffff;\n"
"        padding: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"        background-color: #4c86ff;\n"
"        border: 1px solid #5a5a5a;\n"
"    }")

        self.retranslateUi(Form)
        QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_username.setText(_translate("Form", "Username"))
        self.label_password.setText(_translate("Form", "Password"))
        self.pushButton_create.setText(_translate("Form", "Create!"))
        self.label_password_2.setText(_translate("Form", "Confirm Password"))